#!/bin/bash

PACKAGE_VERSION=`grep '"version":' ./package.json | cut -d '"' -f4`
ANDROID_GRADLE_VERSION=`grep "versionName " ./android/app/build.gradle | cut -d '"' -f2`
TEMP_IOS_VAR=`perl -n -e '/MARKETING_VERSION = (.*);/ && print "$1\n"' ./ios/HathorMobile.xcodeproj/project.pbxproj`
IOS_PROJECT_VERSION_1=`echo $TEMP_IOS_VAR | awk '{print $1}'`
IOS_PROJECT_VERSION_2=`echo $TEMP_IOS_VAR | awk '{print $2}'`

# For debugging:
# echo x${SRC_VERSION}x
# echo x${ELECTRON_VERSION}x
# echo x${PACKAGE_VERSION}x

EXITCODE=0

if [[ x${PACKAGE_VERSION}x != x${ANDROID_GRADLE_VERSION}x ]]; then
	echo Version different in package.json and android/app/build.gradle
	EXITCODE=-1
fi

if [[ x${PACKAGE_VERSION}x != x${IOS_PROJECT_VERSION_1}x ]]; then
	echo Version different in package.json and first MARKETING_VERSION on ios/HathorMobile.xcodeproj/project.pbxproj
	EXITCODE=-1
fi

if [[ x${PACKAGE_VERSION}x != x${IOS_PROJECT_VERSION_2}x ]]; then
	echo Version different in package.json and second MARKETING_VERSION on ios/HathorMobile.xcodeproj/project.pbxproj
	EXITCODE=-1
fi

exit $EXITCODE