/**
 * Mobile shielded crypto provider using HathorCtCryptoModule native module.
 * All methods return Promises (RN bridge is async).
 * Implements the IShieldedCryptoProvider interface from wallet-lib.
 */
import { NativeModules } from 'react-native';

const { HathorCtCryptoModule } = NativeModules;

function bufToArr(buf) {
  return Array.from(buf);
}

function arrToBuf(arr) {
  return Buffer.from(arr);
}

export function createMobileShieldedCryptoProvider() {
  if (!HathorCtCryptoModule) {
    throw new Error('HathorCtCryptoModule native module not available');
  }

  return {
    async generateRandomBlindingFactor() {
      // The native module generates blinding factors internally in createShieldedOutput.
      // For explicit generation, we use the native createShieldedOutput with a dummy value
      // and extract the blinding factor. This ensures it's a valid secp256k1 scalar
      // generated by Rust's secure RNG.
      //
      // TODO: Add a dedicated generateRandomBlindingFactor to the native module.
      const dummyPubkey = Buffer.alloc(33, 0x02);
      const dummyToken = Buffer.alloc(32, 0);
      const result = await HathorCtCryptoModule.createShieldedOutput(
        1, bufToArr(dummyPubkey), bufToArr(dummyToken), false,
      );
      return arrToBuf(result.blindingFactor);
    },

    async createAmountShieldedOutput(value, recipientPubkey, tokenUid, valueBlindingFactor) {
      // Use createShieldedOutputWithBlinding to pass the caller-provided VBF.
      // fullyShielded=false → AmountShielded (token visible).
      const result = await HathorCtCryptoModule.createShieldedOutputWithBlinding(
        Number(value), bufToArr(recipientPubkey), bufToArr(tokenUid),
        false, bufToArr(valueBlindingFactor),
      );
      return {
        ephemeralPubkey: arrToBuf(result.ephemeralPubkey),
        commitment: arrToBuf(result.commitment),
        rangeProof: arrToBuf(result.rangeProof),
        blindingFactor: arrToBuf(result.blindingFactor),
      };
    },

    async createShieldedOutputWithBothBlindings(value, recipientPubkey, tokenUid, vbf, abf) {
      const result = await HathorCtCryptoModule.createShieldedOutputWithBothBlindings(
        Number(value), bufToArr(recipientPubkey), bufToArr(tokenUid),
        bufToArr(vbf), bufToArr(abf),
      );
      return {
        ephemeralPubkey: arrToBuf(result.ephemeralPubkey),
        commitment: arrToBuf(result.commitment),
        rangeProof: arrToBuf(result.rangeProof),
        blindingFactor: arrToBuf(result.blindingFactor),
        assetCommitment: result.assetCommitment ? arrToBuf(result.assetCommitment) : undefined,
        assetBlindingFactor: result.assetBlindingFactor
          ? arrToBuf(result.assetBlindingFactor) : undefined,
      };
    },

    async rewindAmountShieldedOutput(privateKey, ephemeralPubkey, commitment, rangeProof, tokenUid) {
      // Pass empty array instead of null for assetCommitment — the RN bridge
      // can't convert JS null into NSArray (warns and breaks the call).
      // Swift treats empty arrays as nil before forwarding to UniFFI.
      const result = await HathorCtCryptoModule.decryptShieldedOutput(
        bufToArr(privateKey),
        bufToArr(ephemeralPubkey),
        bufToArr(commitment),
        bufToArr(rangeProof),
        bufToArr(tokenUid),
        [], // no assetCommitment for AmountShielded
      );
      return {
        value: BigInt(result.value),
        blindingFactor: arrToBuf(result.blindingFactor),
      };
    },

    async rewindFullShieldedOutput(
      privateKey, ephemeralPubkey, commitment, rangeProof, assetCommitment
    ) {
      // Pass empty array instead of null for tokenUid (recovered from proof
      // for FullShielded). RN bridge can't marshal null → NSArray.
      const result = await HathorCtCryptoModule.decryptShieldedOutput(
        bufToArr(privateKey),
        bufToArr(ephemeralPubkey),
        bufToArr(commitment),
        bufToArr(rangeProof),
        [], // tokenUid is recovered from rangeproof message
        bufToArr(assetCommitment),
      );
      return {
        value: BigInt(result.value),
        blindingFactor: arrToBuf(result.blindingFactor),
        tokenUid: arrToBuf(result.tokenUid),
        assetBlindingFactor: arrToBuf(result.assetBlindingFactor),
      };
    },

    async computeBalancingBlindingFactor(value, generatorBlindingFactor, inputs, otherOutputs) {
      const result = await HathorCtCryptoModule.computeBalancingBlindingFactorFull(
        Number(value),
        bufToArr(generatorBlindingFactor),
        inputs.map((i) => ({
          value: Number(i.value), vbf: bufToArr(i.vbf), gbf: bufToArr(i.gbf),
        })),
        otherOutputs.map((o) => ({
          value: Number(o.value), vbf: bufToArr(o.vbf), gbf: bufToArr(o.gbf),
        })),
      );
      return arrToBuf(result);
    },

    async deriveTag(tokenUid) {
      const result = await HathorCtCryptoModule.deriveTag(bufToArr(tokenUid));
      return arrToBuf(result);
    },

    async createAssetCommitment(tag, blindingFactor) {
      const result = await HathorCtCryptoModule.createAssetCommitment(
        bufToArr(tag), bufToArr(blindingFactor),
      );
      return arrToBuf(result);
    },

    async createSurjectionProof(codomainTag, codomainBlindingFactor, domain) {
      const domainArr = domain.map((d) => ({
        generator: bufToArr(d.generator),
        tag: bufToArr(d.tag),
        blindingFactor: bufToArr(d.blindingFactor),
      }));
      const result = await HathorCtCryptoModule.createSurjectionProof(
        bufToArr(codomainTag), bufToArr(codomainBlindingFactor), domainArr,
      );
      return arrToBuf(result);
    },

    async deriveEcdhSharedSecret(privkey, pubkey) {
      const result = await HathorCtCryptoModule.deriveEcdhSharedSecret(
        bufToArr(privkey), bufToArr(pubkey),
      );
      return arrToBuf(result);
    },
  };
}
